/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
package AplikasiPerhitunganHari;
import com.toedter.calendar.JCalendar;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.SpinnerNumberModel;

public class FormPerhitunganHari extends javax.swing.JFrame {

    /**
     * Creates new form FormPerhitunganHari
     */
    public FormPerhitunganHari() {
        initComponents();
        initCustomComponents();
        initSpinnerListener();
}

private void initCustomComponents() {
    // Set locale Indonesia
        Locale localeID = new Locale("id", "ID");
    
    // Konfigurasi ComboBox Bulan
    String[] namaBulan = {
        "Januari", "Februari", "Maret", "April", "Mei", "Juni",
        "Juli", "Agustus", "September", "Oktober", "November", "Desember"
    };
    cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(namaBulan));
    
    // Konfigurasi JSpinner untuk tahun
    int tahunSekarang = Calendar.getInstance().get(Calendar.YEAR);
    SpinnerNumberModel modelTahun = new SpinnerNumberModel(
        tahunSekarang,  // nilai awal
        1900,           // nilai minimum
        2100,           // nilai maksimum
        1               // step
    );
    spnTahun.setModel(modelTahun);
    
    // Set locale untuk JCalendar
    jCalendar1.setLocale(localeID);
    jCalendarAwal.setLocale(localeID);
    jCalendarAkhir.setLocale(localeID);
    

    
    // Sinkronisasi JCalendar dengan ComboBox dan Spinner
    sinkronisasiKalender();
}

private void sinkronisasiKalender() {
    // Saat kalender berubah, update combo box dan spinner
    jCalendar1.addPropertyChangeListener("calendar", evt -> {
        Calendar cal = jCalendar1.getCalendar();
        cmbBulan.setSelectedIndex(cal.get(Calendar.MONTH));
        spnTahun.setValue(cal.get(Calendar.YEAR));
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUtama = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        lblBulan = new javax.swing.JLabel();
        cmbBulan = new javax.swing.JComboBox<>();
        lblTahun = new javax.swing.JLabel();
        spnTahun = new javax.swing.JSpinner();
        btnHitung = new javax.swing.JButton();
        pnlPerhitungan = new javax.swing.JPanel();
        lblHasilJumlah = new javax.swing.JLabel();
        lblHasilPertama = new javax.swing.JLabel();
        lblHasilTerakhir = new javax.swing.JLabel();
        lblHasilKabisat = new javax.swing.JLabel();
        pnlSelisih = new javax.swing.JPanel();
        jCalendarAwal = new com.toedter.calendar.JCalendar();
        jCalendarAkhir = new com.toedter.calendar.JCalendar();
        btnHitungSelisih = new javax.swing.JButton();
        lblHasilSelisih = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlUtama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplikasi Perhitungan Hari", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 1, 18))); // NOI18N

        lblBulan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBulan.setText("Pilih Bulan:");

        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTahun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTahun.setText("Pilih Tahun:");

        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        pnlPerhitungan.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Perhitungan"));

        lblHasilJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHasilJumlah.setText("Jumlah Hari: -");

        lblHasilPertama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHasilPertama.setText("Hari Pertama: -");

        lblHasilTerakhir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHasilTerakhir.setText("Hari Terakhir: -");

        lblHasilKabisat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHasilKabisat.setText("Status: -");

        javax.swing.GroupLayout pnlPerhitunganLayout = new javax.swing.GroupLayout(pnlPerhitungan);
        pnlPerhitungan.setLayout(pnlPerhitunganLayout);
        pnlPerhitunganLayout.setHorizontalGroup(
            pnlPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerhitunganLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHasilPertama, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(lblHasilJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHasilTerakhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHasilKabisat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pnlPerhitunganLayout.setVerticalGroup(
            pnlPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerhitunganLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblHasilJumlah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHasilPertama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHasilTerakhir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHasilKabisat)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlSelisih.setBorder(javax.swing.BorderFactory.createTitledBorder("Hitung Selisih Hari"));

        btnHitungSelisih.setText("HITUNG SELISIH");
        btnHitungSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungSelisihActionPerformed(evt);
            }
        });

        lblHasilSelisih.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHasilSelisih.setText("Hasil Selisih: -");

        javax.swing.GroupLayout pnlSelisihLayout = new javax.swing.GroupLayout(pnlSelisih);
        pnlSelisih.setLayout(pnlSelisihLayout);
        pnlSelisihLayout.setHorizontalGroup(
            pnlSelisihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelisihLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSelisihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendarAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSelisihLayout.createSequentialGroup()
                        .addGroup(pnlSelisihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendarAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlSelisihLayout.createSequentialGroup()
                                .addComponent(btnHitungSelisih)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pnlSelisihLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblHasilSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        pnlSelisihLayout.setVerticalGroup(
            pnlSelisihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelisihLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendarAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendarAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHitungSelisih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHasilSelisih)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlUtamaLayout = new javax.swing.GroupLayout(pnlUtama);
        pnlUtama.setLayout(pnlUtamaLayout);
        pnlUtamaLayout.setHorizontalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbBulan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnTahun)
                            .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlPerhitungan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(pnlSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUtamaLayout.setVerticalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBulan)
                    .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTahun)
                    .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHitung)
                .addGap(18, 18, 18)
                .addComponent(pnlPerhitungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addComponent(pnlSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
        // Ambil input dari user
        int bulan = cmbBulan.getSelectedIndex() + 1; // +1 karena index mulai 0
        int tahun = (Integer) spnTahun.getValue();
        
        // Hitung menggunakan YearMonth
        YearMonth yearMonth = YearMonth.of(tahun, bulan);
        int jumlahHari = yearMonth.lengthOfMonth();
        
        // Dapatkan hari pertama dan terakhir
        LocalDate hariPertama = yearMonth.atDay(1);
        LocalDate hariTerakhir = yearMonth.atEndOfMonth();
        
        // Format tanggal
        Locale localeID = new Locale("id", "ID");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy", localeID);
        
        // Nama hari dalam bahasa Indonesia
        String namaHariPertama = hariPertama.getDayOfWeek()
            .getDisplayName(TextStyle.FULL, localeID);
        String namaHariTerakhir = hariTerakhir.getDayOfWeek()
            .getDisplayName(TextStyle.FULL, localeID);
        
        // Cek tahun kabisat
        boolean kabisat = yearMonth.isLeapYear();
        String statusKabisat = kabisat ? "Tahun Kabisat" : "Bukan Tahun Kabisat";
        
        // Tampilkan hasil
        lblHasilJumlah.setText("Jumlah Hari: " + jumlahHari + " hari");
        lblHasilPertama.setText("Hari Pertama: " + hariPertama.format(formatter));
        lblHasilTerakhir.setText("Hari Terakhir: " + hariTerakhir.format(formatter));
        lblHasilKabisat.setText("Status: " + statusKabisat);
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Terjadi kesalahan: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnHitungSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungSelisihActionPerformed
         try {
        // Ambil tanggal dari kedua kalender
        Calendar calAwal = jCalendarAwal.getCalendar();
        Calendar calAkhir = jCalendarAkhir.getCalendar();
        
        // Konversi ke LocalDate
        LocalDate tanggalAwal = LocalDate.of(
            calAwal.get(Calendar.YEAR),
            calAwal.get(Calendar.MONTH) + 1,
            calAwal.get(Calendar.DAY_OF_MONTH)
        );
        
        LocalDate tanggalAkhir = LocalDate.of(
            calAkhir.get(Calendar.YEAR),
            calAkhir.get(Calendar.MONTH) + 1,
            calAkhir.get(Calendar.DAY_OF_MONTH)
        );
        
        // Hitung selisih hari
        long selisihHari = ChronoUnit.DAYS.between(tanggalAwal, tanggalAkhir);
        
        // Format hasil
        Locale localeID = new Locale("id", "ID");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d MMMM yyyy", localeID);
        
        String hasil = String.format(
            "<html><b>Selisih Hari: %d hari</b><br>" +
            "Dari: %s<br>" +
            "Sampai: %s</html>",
            Math.abs(selisihHari),
            tanggalAwal.format(formatter),
            tanggalAkhir.format(formatter)
        );
        
        lblHasilSelisih.setText(hasil);
        
        // Tampilkan peringatan jika tanggal awal > tanggal akhir
        if (selisihHari < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Tanggal awal lebih besar dari tanggal akhir!",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Terjadi kesalahan: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnHitungSelisihActionPerformed

    private void initSpinnerListener() {
    spnTahun.addChangeListener(e -> {
        // Update kalender saat spinner berubah
        int tahun = (Integer) spnTahun.getValue();
        int bulan = cmbBulan.getSelectedIndex();
        
        Calendar cal = jCalendar1.getCalendar();
        cal.set(Calendar.YEAR, tahun);
        cal.set(Calendar.MONTH, bulan);
        jCalendar1.setCalendar(cal);
        
        // Auto-hitung jika diinginkan
        // btnHitungActionPerformed(null);
    });
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPerhitunganHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitungSelisih;
    private javax.swing.JComboBox<String> cmbBulan;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendarAkhir;
    private com.toedter.calendar.JCalendar jCalendarAwal;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHasilJumlah;
    private javax.swing.JLabel lblHasilKabisat;
    private javax.swing.JLabel lblHasilPertama;
    private javax.swing.JLabel lblHasilSelisih;
    private javax.swing.JLabel lblHasilTerakhir;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JPanel pnlPerhitungan;
    private javax.swing.JPanel pnlSelisih;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JSpinner spnTahun;
    // End of variables declaration//GEN-END:variables
}
